/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ShopCategorySubcategoryRouteImport } from './routes/shop.$category.$subcategory'
import { Route as ShopCategorySubcategorySlugRouteImport } from './routes/shop.$category.$subcategory.$slug'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategorySubcategoryRoute = ShopCategorySubcategoryRouteImport.update({
  id: '/shop/$category/$subcategory',
  path: '/shop/$category/$subcategory',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategorySubcategorySlugRoute =
  ShopCategorySubcategorySlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ShopCategorySubcategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order/$id': typeof OrderIdRoute
  '/shop/$category/$subcategory': typeof ShopCategorySubcategoryRouteWithChildren
  '/shop/$category/$subcategory/$slug': typeof ShopCategorySubcategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order/$id': typeof OrderIdRoute
  '/shop/$category/$subcategory': typeof ShopCategorySubcategoryRouteWithChildren
  '/shop/$category/$subcategory/$slug': typeof ShopCategorySubcategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order/$id': typeof OrderIdRoute
  '/shop/$category/$subcategory': typeof ShopCategorySubcategoryRouteWithChildren
  '/shop/$category/$subcategory/$slug': typeof ShopCategorySubcategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/order/$id'
    | '/shop/$category/$subcategory'
    | '/shop/$category/$subcategory/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/order/$id'
    | '/shop/$category/$subcategory'
    | '/shop/$category/$subcategory/$slug'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/order/$id'
    | '/shop/$category/$subcategory'
    | '/shop/$category/$subcategory/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OrderIdRoute: typeof OrderIdRoute
  ShopCategorySubcategoryRoute: typeof ShopCategorySubcategoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category/$subcategory': {
      id: '/shop/$category/$subcategory'
      path: '/shop/$category/$subcategory'
      fullPath: '/shop/$category/$subcategory'
      preLoaderRoute: typeof ShopCategorySubcategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category/$subcategory/$slug': {
      id: '/shop/$category/$subcategory/$slug'
      path: '/$slug'
      fullPath: '/shop/$category/$subcategory/$slug'
      preLoaderRoute: typeof ShopCategorySubcategorySlugRouteImport
      parentRoute: typeof ShopCategorySubcategoryRoute
    }
  }
}

interface ShopCategorySubcategoryRouteChildren {
  ShopCategorySubcategorySlugRoute: typeof ShopCategorySubcategorySlugRoute
}

const ShopCategorySubcategoryRouteChildren: ShopCategorySubcategoryRouteChildren =
  {
    ShopCategorySubcategorySlugRoute: ShopCategorySubcategorySlugRoute,
  }

const ShopCategorySubcategoryRouteWithChildren =
  ShopCategorySubcategoryRoute._addFileChildren(
    ShopCategorySubcategoryRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OrderIdRoute: OrderIdRoute,
  ShopCategorySubcategoryRoute: ShopCategorySubcategoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
